[package]
name = "crisp-zk-witness-generator"
version = "0.1.0"
description = "JavaScript library with WASM bindings for ZK witness generation."
authors = ["Cedoor <me@cedoor.dev>"]
license = "MIT"
repository = "https://github.com/cedoor/crisp-witness-generator"

[build]
target = "web"
out-dir = "pkg"
